<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\Index\IndexType;
use Doctrine\DBAL\Schema\PrimaryKeyConstraint;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Types;
use Doctrine\Migrations\AbstractMigration;

final class Version20261007183820 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create marketplace orders with unique shop/marketplace identity and delivery totals in kopecks';
    }

    public function up(Schema $schema): void
    {
        $table = Table::editor()
            ->setUnquotedName('marketplace_order')
            ->setOptions(['charset' => 'utf8mb4'])
            ->setColumns(
                Column::editor()->setUnquotedName('id')->setTypeName(Types::INTEGER)->setAutoincrement(true)->create(),
                Column::editor()->setUnquotedName('shop_id')->setTypeName(Types::STRING)->setLength(64)->setCollation('utf8mb4_bin')->create(),
                Column::editor()->setUnquotedName('marketplace_id')->setTypeName(Types::STRING)->setLength(255)->setCollation('utf8mb4_bin')->create(),
                Column::editor()->setUnquotedName('status')->setTypeName(Types::STRING)->setLength(20)->create(),
                Column::editor()->setUnquotedName('created_at')->setTypeName(Types::DATETIME_IMMUTABLE)->create(),
                Column::editor()->setUnquotedName('customer_name')->setTypeName(Types::STRING)->setLength(255)->create(),
                Column::editor()->setUnquotedName('customer_phone')->setTypeName(Types::STRING)->setLength(12)->create(),
                Column::editor()->setUnquotedName('delivery_type')->setTypeName(Types::STRING)->setLength(20)->create(),
                Column::editor()->setUnquotedName('district')->setTypeName(Types::STRING)->setLength(64)->setNotNull(false)->create(),
                Column::editor()->setUnquotedName('address')->setTypeName(Types::TEXT)->setNotNull(false)->create(),
                Column::editor()->setUnquotedName('delivery_starts_at')->setTypeName(Types::DATETIME_IMMUTABLE)->setNotNull(false)->create(),
                Column::editor()->setUnquotedName('delivery_ends_at')->setTypeName(Types::DATETIME_IMMUTABLE)->setNotNull(false)->create(),
                Column::editor()->setUnquotedName('items')->setTypeName(Types::JSON)->create(),
                Column::editor()->setUnquotedName('items_total_cents')->setTypeName(Types::BIGINT)->create(),
                Column::editor()->setUnquotedName('marketplace_total_cents')->setTypeName(Types::BIGINT)->create(),
                Column::editor()->setUnquotedName('delivery_cost_cents')->setTypeName(Types::BIGINT)->create(),
                Column::editor()->setUnquotedName('grand_total_cents')->setTypeName(Types::BIGINT)->create(),
                Column::editor()->setUnquotedName('needs_review')->setTypeName(Types::BOOLEAN)->create(),
            )
            ->setPrimaryKeyConstraint(
                PrimaryKeyConstraint::editor()->setUnquotedColumnNames('id')->create(),
            )
            ->setIndexes(
                Index::editor()->setUnquotedName('idx_shop_status_created')
                    ->setUnquotedColumnNames('shop_id', 'status', 'created_at')->create(),
                Index::editor()->setUnquotedName('uniq_shop_marketplace')->setType(IndexType::UNIQUE)
                    ->setUnquotedColumnNames('shop_id', 'marketplace_id')->create(),
            )
            ->create();

        $this->scheduleSchemaChanges($schema, $schema->edit()->addTable($table)->create());
    }

    public function down(Schema $schema): void
    {
        $this->scheduleSchemaChanges($schema, $schema->edit()->dropTableByUnquotedName('marketplace_order')->create());
    }

    private function scheduleSchemaChanges(Schema $fromSchema, Schema $toSchema): void
    {
        // Editors return a new schema; Migrations 3 requires its changes to be
        // queued explicitly. Every statement below is generated by Doctrine.
        $diff = $this->sm->createComparator()->compareSchemas($fromSchema, $toSchema);
        foreach ($this->platform->getAlterSchemaSQL($diff) as $statement) {
            $this->addSql($statement);
        }
    }
}
